name: Release
on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: 'Checkout'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: 'Use NodeJS 14'
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install dependencies
              run: |
                  yarn install --immutable

            - name: Build app
              run: yarn build

            - name: Semantic release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor}}@users.noreply.github.com"

                  npx semantic-release
